apiVersion: v1
kind: Pod
metadata:
  name: no-limit-resource
  labels:
    owner: me.agilebank.demo
    team: foopay
    app: opa-service
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"

