apiVersion: v1
kind: Pod
metadata:
  name: no-required-label
  labels:
    owner: me.agilebank.demo
    team: foo
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "300Mi"
