apiVersion: v1
kind: Pod
metadata:
  name: existing-opa
  labels:
    owner: me.agilebank.demo
    team: foopay
    app: opa-service
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "384Mi"
