apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: foopayk8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: FoopayK8sRequiredLabels
        listKind: FoopayK8sRequiredLabels
        plural: foopayk8srequiredlabels
        singular: foopayk8srequiredlabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            message:
              type: string
            labels:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package foopayk8srequiredlabels

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_].key}
          missing := required - provided
          count(missing) > 0
          msg := sprintf("You must provide labels: %v", [missing])
        }

        violation[{"msg": msg}] {
          value := input.request.object.metadata.labels[key]
          expected := input.parameters.labels[_]
          expected.key == key
          expected.value == ""

          msg := sprintf("You must provide label <%v> with value <%>", [expected.key, expected.value])
        }

        violation[{"msg": msg}] {
          value := input.request.object.metadata.labels[key]
          expected := input.parameters.labels[_]
          expected.key == key
          expected.value == value

          msg := sprintf("You must provide label <%v> with value <%>", [expected.key, expected.value])
        }
